version: "2"

services:
  master:
    image: foamscience/foam-extend-4.1-openmpi
    ports: 
      - "2222::22"
    links: 
      - slave
    volumes:
      - data:/data
    networks:
      - net

  slave:
    image: foamscience/foam-extend-4.1-openmpi
    restart: unless-stopped:0
    volumes:
      - data:/data
    networks:
      - net

volumes:
  data:

networks:
  net:
    driver: bridge
