master:
  image: fe4-mpi
  ports: 
   - "22"
  volumes:
   - data:/data
  links: 
   - slave

slave: 
  image: fe4-mpi
  volumes:
   - data:/data

volumes:
  data:
    external: true

# version: "2"

# services:
#   master:
#     image: fe4-mpi
#     ports: 
#       - "22"
#     links: 
#       - slave
#     volumes:
#       - data:/data
#     networks:
#       - net

#   slave:
#     image: fe4-mpi
#     networks:
#       - net

# volumes:
#   data:
#     external: true

# networks:
#   net:
#     driver: bridge
