name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag foamscience/foam-extend-4.1-openmpi:latest
    - name: Push the Docker image
      run: docker push foamscience/foam-extend-4.1-openmpi:latest
